name: Trigger auto deployment for street-food-information

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/street-food-information-AutoDeployTrigger-a120fe27-e6c2-41ac-baf0-1fe341be98df.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.STREETFOODINFORMATION_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.STREETFOODINFORMATION_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.STREETFOODINFORMATION_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: 
          registryUsername: ${{ secrets.STREETFOODINFORMATION_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.STREETFOODINFORMATION_REGISTRY_PASSWORD }}
          containerAppName: street-food-information
          resourceGroup: StreetFoodV2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


